name: pricecompare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  #dio: ^5.0.4  # For handling API calls
  #image_picker: ^0.8.7+4  # For image uploads
  #cached_network_image: ^3.2.3  # For caching images
  #barcode_scan2: ^4.1.4
  #cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

