name: pricecompare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  heroicons: ^0.10.0
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Jersey10
      fonts:
        - asset: fonts/Jersey10-Regular.ttf 
    
  assets: 
    - assets/

